/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.potromonpro.ui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.itson.potromonpro.entidades.Potromon;

/**
 *
 * @author dzlan
 */
public class PotromonListado extends javax.swing.JFrame {

    /**
     * Creates new form PotromonListado
     */
    public PotromonListado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPotromon = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        smrPuntaje = new javax.swing.JButton();
        rstPuntaje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Lista de Potromon");

        tblPotromon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Entrenador", "Puntaje"
            }
        ));
        jScrollPane1.setViewportView(tblPotromon);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnConsulta.setText("Consulta");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        smrPuntaje.setText("Sumar Puntaje");
        smrPuntaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smrPuntajeActionPerformed(evt);
            }
        });

        rstPuntaje.setText("Restar Puntaje");
        rstPuntaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rstPuntajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnConsulta)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(smrPuntaje)
                        .addGap(170, 170, 170)
                        .addComponent(rstPuntaje)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(60, 60, 60)
                        .addComponent(btnConsulta)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(smrPuntaje)
                    .addComponent(rstPuntaje))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        PotromonForm form = new PotromonForm(this, true, 0);
        form.setVisible(true);

        cargarTable();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int renglon = tblPotromon.getSelectedRow();
        int idPotromon = Integer.parseInt(tblPotromon.getModel().getValueAt(renglon, 0).toString());

        PotromonForm form = new PotromonForm(this, true,  idPotromon);
        form.setVisible(true);

        cargarTable();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int renglon = tblPotromon.getSelectedRow();
        int idServicio = Integer.parseInt(tblPotromon.getModel().getValueAt(renglon, 0).toString());

        if (JOptionPane.showConfirmDialog(this, "¿Estas seguro que desea eliminar el  Potromon?", "Eliminar registro", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        }
        if (Potromon.delete(idServicio)) {
            JOptionPane.showMessageDialog(this, "El Potromon se elimino con exito", "Registro eliminado", JOptionPane.INFORMATION_MESSAGE);
            cargarTable();

            if (Potromon.delete(idServicio)) {
                JOptionPane.showMessageDialog(this, "Ocurrio un error al eliminar el Potromon", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarTable();
        tblPotromon.removeColumn(tblPotromon.getColumnModel().getColumn(0));
    }//GEN-LAST:event_formWindowOpened

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        int renglon = tblPotromon.getSelectedRow();

        if (renglon == -1) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona un registro", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int potromon_id = Integer.parseInt(tblPotromon.getModel().getValueAt(renglon, 0).toString());

        PotromonConsulta form = new PotromonConsulta(this, true, potromon_id);
        form.setVisible(true);


    }//GEN-LAST:event_btnConsultaActionPerformed

    private void smrPuntajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smrPuntajeActionPerformed
  int selectedRow = tblPotromon.getSelectedRow();
    if (selectedRow != -1) {
        int potromonId = Integer.parseInt(tblPotromon.getModel().getValueAt(selectedRow, 0).toString());
        Potromon p = Potromon.getById(potromonId); 

        int nuevoPuntaje = p.getPuntaje() + 5; 
        Potromon.actualizarPuntaje(potromonId, nuevoPuntaje); 

        
        tblPotromon.getModel().setValueAt(nuevoPuntaje, selectedRow, 3); 
    } else {
        JOptionPane.showMessageDialog(this, "Selecciona un potromon");
    }

       
   
    }//GEN-LAST:event_smrPuntajeActionPerformed

    private void rstPuntajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rstPuntajeActionPerformed
   int selectedRow = tblPotromon.getSelectedRow();
    if (selectedRow != -1) {
        int potromonId = Integer.parseInt(tblPotromon.getModel().getValueAt(selectedRow, 0).toString());
        Potromon p = Potromon.getById(potromonId); 

        int nuevoPuntaje = Math.max(0, p.getPuntaje() - 5); 
        Potromon.actualizarPuntaje(potromonId, nuevoPuntaje);

        
        tblPotromon.getModel().setValueAt(nuevoPuntaje, selectedRow, 3); 
    } else {
        JOptionPane.showMessageDialog(this, "Selecciona un potromon");
    }

    }//GEN-LAST:event_rstPuntajeActionPerformed

    private void cargarTable() {
        List<Potromon> potromones = Potromon.getAll();
        DefaultTableModel modeloTabla = (DefaultTableModel) tblPotromon.getModel();
        modeloTabla.setRowCount(0);
        for (Potromon r : potromones) {
            modeloTabla.addRow(new Object[]{
                r.getId(),
                r.getNombre(),
                r.getEntrenador().getNombre(),
                r.getPuntaje()
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PotromonListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PotromonListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PotromonListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PotromonListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PotromonListado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rstPuntaje;
    private javax.swing.JButton smrPuntaje;
    private javax.swing.JTable tblPotromon;
    // End of variables declaration//GEN-END:variables
}
